export const APP_NAME = 'AURA Learn';
export const APP_TAGLINE = 'Your Personal AI University';
export const APP_DESCRIPTION = 'Learn anything with an AI professor that teaches like a real human instructor.';

export const NAV_LINKS = [
  { label: 'Home', href: '/' },
  { label: 'Explore Courses', href: '/courses' },
  { label: 'AI Teacher', href: '/ai-teacher' },
  { label: 'Live Classroom', href: '/classroom' },
  { label: 'Coding Lab', href: '/coding-lab' },
  { label: 'Dashboard', href: '/dashboard' },
  { label: 'Career Roadmaps', href: '/roadmap' },
  { label: 'Certificates', href: '/certificates' },
  { label: 'Community', href: '/community' },
  { label: 'Help Center', href: '/help' },
];

export const COURSE_CATEGORIES = [
  { id: 'programming', label: 'Programming', icon: 'Code2', color: '#6366f1' },
  { id: 'artificial-intelligence', label: 'AI & Machine Learning', icon: 'Brain', color: '#8b5cf6' },
  { id: 'data-science', label: 'Data Science', icon: 'BarChart3', color: '#06b6d4' },
  { id: 'mathematics', label: 'Mathematics', icon: 'Sigma', color: '#f59e0b' },
  { id: 'science', label: 'Science', icon: 'Flask', color: '#10b981' },
  { id: 'engineering', label: 'Engineering', icon: 'Settings2', color: '#ef4444' },
  { id: 'business', label: 'Business', icon: 'Briefcase', color: '#3b82f6' },
  { id: 'finance', label: 'Finance', icon: 'TrendingUp', color: '#14b8a6' },
  { id: 'design', label: 'Design', icon: 'Palette', color: '#ec4899' },
  { id: 'languages', label: 'Languages', icon: 'Languages', color: '#a855f7' },
  { id: 'cybersecurity', label: 'Cybersecurity', icon: 'Shield', color: '#22c55e' },
  { id: 'cloud-computing', label: 'Cloud Computing', icon: 'Cloud', color: '#0ea5e9' },
];

export const LEVELS = [
  { id: 'beginner', label: 'Beginner', color: '#22c55e' },
  { id: 'intermediate', label: 'Intermediate', color: '#f59e0b' },
  { id: 'advanced', label: 'Advanced', color: '#ef4444' },
  { id: 'expert', label: 'Expert', color: '#8b5cf6' },
];

export const LANGUAGES = [
  { code: 'en', name: 'English', native: 'English' },
  { code: 'es', name: 'Spanish', native: 'Español' },
  { code: 'fr', name: 'French', native: 'Français' },
  { code: 'de', name: 'German', native: 'Deutsch' },
  { code: 'zh', name: 'Chinese', native: '中文' },
  { code: 'ja', name: 'Japanese', native: '日本語' },
  { code: 'ko', name: 'Korean', native: '한국어' },
  { code: 'ar', name: 'Arabic', native: 'العربية' },
  { code: 'hi', name: 'Hindi', native: 'हिन्दी' },
  { code: 'pt', name: 'Portuguese', native: 'Português' },
  { code: 'ru', name: 'Russian', native: 'Русский' },
  { code: 'it', name: 'Italian', native: 'Italiano' },
];

export const VOICE_OPTIONS = [
  { id: 'male-1', label: 'Professor Marcus', gender: 'male' },
  { id: 'male-2', label: 'Dr. James', gender: 'male' },
  { id: 'female-1', label: 'Professor Sophia', gender: 'female' },
  { id: 'female-2', label: 'Dr. Elena', gender: 'female' },
];

export const AMBIENT_SOUNDS = [
  { id: 'none', label: 'None', icon: 'VolumeX' },
  { id: 'classroom', label: 'Classroom', icon: 'School' },
  { id: 'rain', label: 'Rain', icon: 'CloudRain' },
  { id: 'library', label: 'Library', icon: 'BookOpen' },
  { id: 'instrumental', label: 'Soft Music', icon: 'Music' },
  { id: 'white-noise', label: 'White Noise', icon: 'Waves' },
  { id: 'nature', label: 'Nature', icon: 'TreePine' },
  { id: 'coffee-shop', label: 'Coffee Shop', icon: 'Coffee' },
];

export const SUBSCRIPTION_PLANS = [
  {
    id: 'free',
    name: 'Free',
    price: 0,
    description: 'Get started with basic courses',
    features: [
      'Access to free courses',
      'Basic AI teaching',
      'Community access',
      '1 project per month',
    ],
    limitations: ['Limited quizzes', 'No certificates', 'No voice narration'],
    popular: false,
  },
  {
    id: 'premium',
    name: 'Premium',
    price: 19.99,
    description: 'Unlock unlimited learning',
    features: [
      'All courses included',
      'Advanced AI teaching',
      'Voice narration',
      'Unlimited projects',
      'Certificates',
      'Priority support',
    ],
    limitations: [],
    popular: true,
  },
  {
    id: 'pro',
    name: 'Pro',
    price: 39.99,
    description: 'For serious learners',
    features: [
      'Everything in Premium',
      'Career mentorship',
      'Interview preparation',
      'Resume review',
      '1-on-1 AI sessions',
      'Early access features',
    ],
    limitations: [],
    popular: false,
  },
  {
    id: 'enterprise',
    name: 'Enterprise',
    price: 99.99,
    description: 'For teams and organizations',
    features: [
      'Everything in Pro',
      'Team management',
      'Custom curriculum',
      'API access',
      'Dedicated support',
      'Analytics dashboard',
      'SSO integration',
    ],
    limitations: [],
    popular: false,
  },
];

export const MOCK_COURSES = [
  {
    id: '1',
    title: 'Complete Python Programming',
    description: 'Master Python from zero to advanced with hands-on projects and real-world applications.',
    category: 'programming' as const,
    level: 'beginner' as const,
    thumbnail: '/courses/python.jpg',
    instructor: { name: 'Dr. Sarah Chen', avatar: '/avatars/teacher1.jpg', title: 'AI Research Scientist' },
    rating: 4.8,
    enrolledStudents: 15420,
    totalLessons: 120,
    totalDuration: 3600,
    price: 0,
    tags: ['Python', 'Programming', 'Beginner Friendly'],
  },
  {
    id: '2',
    title: 'Deep Learning & Neural Networks',
    description: 'Build neural networks from scratch and master deep learning with PyTorch and TensorFlow.',
    category: 'artificial-intelligence' as const,
    level: 'advanced' as const,
    thumbnail: '/courses/deep-learning.jpg',
    instructor: { name: 'Prof. Alex Kumar', avatar: '/avatars/teacher2.jpg', title: 'Deep Learning Engineer' },
    rating: 4.9,
    enrolledStudents: 8930,
    totalLessons: 85,
    totalDuration: 4800,
    price: 49.99,
    tags: ['Deep Learning', 'Neural Networks', 'PyTorch', 'TensorFlow'],
  },
  {
    id: '3',
    title: 'Full-Stack Web Development',
    description: 'Build modern web applications with React, Next.js, Node.js, and TypeScript.',
    category: 'programming' as const,
    level: 'intermediate' as const,
    thumbnail: '/courses/webdev.jpg',
    instructor: { name: 'Maria Rodriguez', avatar: '/avatars/teacher3.jpg', title: 'Full-Stack Developer' },
    rating: 4.7,
    enrolledStudents: 12300,
    totalLessons: 150,
    totalDuration: 5400,
    price: 29.99,
    tags: ['React', 'Next.js', 'Node.js', 'TypeScript', 'Full-Stack'],
  },
  {
    id: '4',
    title: 'Data Science & Analytics',
    description: 'Learn data analysis, visualization, statistics, and machine learning with Python.',
    category: 'data-science' as const,
    level: 'beginner' as const,
    thumbnail: '/courses/datascience.jpg',
    instructor: { name: 'Dr. James Wilson', avatar: '/avatars/teacher4.jpg', title: 'Data Scientist' },
    rating: 4.6,
    enrolledStudents: 18750,
    totalLessons: 95,
    totalDuration: 3200,
    price: 0,
    tags: ['Data Science', 'Python', 'Statistics', 'Machine Learning'],
  },
  {
    id: '5',
    title: 'Cybersecurity Fundamentals',
    description: 'Protect systems and networks from cyber threats with hands-on security training.',
    category: 'cybersecurity' as const,
    level: 'intermediate' as const,
    thumbnail: '/courses/cybersecurity.jpg',
    instructor: { name: 'Marcus Johnson', avatar: '/avatars/teacher5.jpg', title: 'Security Engineer' },
    rating: 4.8,
    enrolledStudents: 7650,
    totalLessons: 70,
    totalDuration: 2800,
    price: 39.99,
    tags: ['Cybersecurity', 'Network Security', 'Ethical Hacking'],
  },
  {
    id: '6',
    title: 'Business Strategy & Management',
    description: 'Develop strategic thinking and management skills for modern businesses.',
    category: 'business' as const,
    level: 'intermediate' as const,
    thumbnail: '/courses/business.jpg',
    instructor: { name: 'Prof. Emily Park', avatar: '/avatars/teacher6.jpg', title: 'Business Strategist' },
    rating: 4.5,
    enrolledStudents: 5430,
    totalLessons: 60,
    totalDuration: 2400,
    price: 19.99,
    tags: ['Business', 'Strategy', 'Management', 'Leadership'],
  },
];

export const FAQ_ITEMS = [
  {
    question: 'How does AI teaching work?',
    answer: 'AURA Learn uses advanced AI agents that work together to create personalized learning experiences. The AI analyzes your learning style, progress, and goals to adapt teaching in real-time.',
  },
  {
    question: 'Can I learn programming without experience?',
    answer: 'Yes! Our platform supports learners at all levels. The AI automatically adjusts the curriculum to your skill level, starting from basics if you are a complete beginner.',
  },
  {
    question: 'Is the platform available in multiple languages?',
    answer: 'Yes, AURA Learn supports 12+ languages. All lessons, quizzes, notes, and AI conversations automatically adapt to your selected language.',
  },
  {
    question: 'How are certificates issued?',
    answer: 'Certificates are automatically generated upon course completion with a unique verification ID. They can be shared on LinkedIn and verified by employers.',
  },
  {
    question: 'Does the AI remember my learning history?',
    answer: 'Yes, the AI maintains a comprehensive learning profile, remembering your progress, strengths, weaknesses, and preferences to personalize every lesson.',
  },
  {
    question: 'Can I ask questions during a lesson?',
    answer: 'Absolutely! You can interrupt any lesson with questions via voice or text. The AI will answer on a side panel and then resume teaching seamlessly.',
  },
];

export const TESTIMONIALS = [
  {
    id: '1',
    name: 'Alex Thompson',
    role: 'Software Engineer',
    avatar: '/avatars/student1.jpg',
    content: 'AURA Learn completely transformed how I learn. The AI teacher explains concepts better than any human instructor I have had.',
    rating: 5,
  },
  {
    id: '2',
    name: 'Priya Sharma',
    role: 'Data Scientist',
    avatar: '/avatars/student2.jpg',
    content: 'The coding lab with real-time AI guidance helped me build production-ready skills. Highly recommended for aspiring developers.',
    rating: 5,
  },
  {
    id: '3',
    name: 'James Miller',
    role: 'AI Researcher',
    avatar: '/avatars/student3.jpg',
    content: 'The deep learning course with interactive whiteboard teaching made complex concepts intuitive. The AI assistant is incredible.',
    rating: 5,
  },
  {
    id: '4',
    name: 'Sofia Garcia',
    role: 'Product Manager',
    avatar: '/avatars/student4.jpg',
    content: 'Being able to learn in Spanish with full AI support is amazing. The automated notes and flashcards save me hours of study time.',
    rating: 5,
  },
];

export const TEACHER_STYLES = [
  {
    id: 'professor',
    name: 'Professor',
    title: 'The Classic Educator',
    tagline: 'Structured, thorough, and comprehensive teaching with deep explanations.',
    description: 'Like a university professor, I teach with well-structured lessons, building from fundamentals to advanced concepts. I use formal explanations, cite research, and ensure you have a deep theoretical understanding before moving to practice.',
    icon: 'GraduationCap',
    color: '#6366f1',
    voiceStyle: 'Formal, articulate, measured',
    teachingApproach: 'Structured',
    explanationDepth: 'comprehensive' as const,
    useAnalogies: true,
    useExamples: true,
    useHumor: false,
    encourageQuestions: true,
    pace: 'moderate' as const,
  },
  {
    id: 'coach',
    name: 'Coach',
    title: 'The Motivational Mentor',
    tagline: 'Practical, hands-on learning with real-world projects and encouragement.',
    description: 'I focus on practical application and building real projects. My teaching is action-oriented with lots of exercises, challenges, and encouragement. I push you to code, build, and create while providing supportive guidance.',
    icon: 'Zap',
    color: '#f59e0b',
    voiceStyle: 'Energetic, encouraging, direct',
    teachingApproach: 'Hands-on',
    explanationDepth: 'moderate' as const,
    useAnalogies: true,
    useExamples: true,
    useHumor: false,
    encourageQuestions: true,
    pace: 'fast' as const,
  },
  {
    id: 'friend',
    name: 'Friend',
    title: 'The Friendly Guide',
    tagline: 'Conversational, relatable teaching with humor and everyday analogies.',
    description: 'Learning should feel natural and fun! I teach like a knowledgeable friend explaining things over coffee. I use casual language, humor, and relatable analogies. No question is too silly — I create a safe, judgment-free learning space.',
    icon: 'Heart',
    color: '#ec4899',
    voiceStyle: 'Warm, casual, friendly',
    teachingApproach: 'Conversational',
    explanationDepth: 'basic' as const,
    useAnalogies: true,
    useExamples: true,
    useHumor: true,
    encourageQuestions: true,
    pace: 'slow' as const,
  },
  {
    id: 'expert',
    name: 'Expert',
    title: 'The Industry Veteran',
    tagline: 'Advanced insights, best practices, and professional-grade teaching.',
    description: 'I teach like a senior engineer or industry expert sharing years of experience. I focus on best practices, design patterns, performance optimization, and production-ready code. Perfect for experienced learners who want to level up.',
    icon: 'Brain',
    color: '#8b5cf6',
    voiceStyle: 'Authoritative, precise, confident',
    teachingApproach: 'Advanced',
    explanationDepth: 'deep' as const,
    useAnalogies: false,
    useExamples: true,
    useHumor: false,
    encourageQuestions: false,
    pace: 'fast' as const,
  },
  {
    id: 'simplifier',
    name: 'Simplifier',
    title: 'The Clear Explainer',
    tagline: 'Complex topics made simple with visual explanations and step-by-step breakdowns.',
    description: 'I specialize in taking the most complex topics and breaking them down into simple, digestible pieces. I use visual explanations, step-by-step breakdowns, and the "explain like I\'m 5" approach. Perfect for beginners or tough topics.',
    icon: 'BookOpen',
    color: '#06b6d4',
    voiceStyle: 'Patient, clear, slow-paced',
    teachingApproach: 'Step-by-step',
    explanationDepth: 'basic' as const,
    useAnalogies: true,
    useExamples: true,
    useHumor: false,
    encourageQuestions: true,
    pace: 'slow' as const,
  },
] as const;

export const ACHIEVEMENTS_LIST = [
  {
    id: 'first-lesson',
    title: 'First Steps',
    description: 'Complete your first lesson',
    icon: 'Footprints',
    xpReward: 50,
    category: 'learning' as const,
  },
  {
    id: 'streak-7',
    title: 'Week Warrior',
    description: 'Maintain a 7-day learning streak',
    icon: 'Flame',
    xpReward: 200,
    category: 'streak' as const,
  },
  {
    id: 'quiz-perfect',
    title: 'Perfect Score',
    description: 'Get 100% on any quiz',
    icon: 'Award',
    xpReward: 150,
    category: 'quiz' as const,
  },
  {
    id: 'code-master',
    title: 'Code Master',
    description: 'Complete 10 coding exercises',
    icon: 'Code2',
    xpReward: 300,
    category: 'coding' as const,
  },
  {
    id: 'course-complete',
    title: 'Graduate',
    description: 'Complete an entire course',
    icon: 'GraduationCap',
    xpReward: 500,
    category: 'learning' as const,
  },
  {
    id: 'project-pro',
    title: 'Project Pro',
    description: 'Complete 5 projects',
    icon: 'FolderKanban',
    xpReward: 400,
    category: 'project' as const,
  },
];

export const ROADMAPS = [
  {
    id: 'frontend-dev',
    title: 'Frontend Developer',
    description: 'Master modern frontend development with React, TypeScript, and modern CSS',
    courses: ['HTML/CSS Basics', 'JavaScript Fundamentals', 'React Mastery', 'TypeScript Deep Dive', 'Advanced CSS'],
    duration: '6-8 months',
    level: 'beginner' as const,
  },
  {
    id: 'data-scientist',
    title: 'Data Scientist',
    description: 'Become a data scientist with Python, statistics, and machine learning',
    courses: ['Python Programming', 'Statistics & Probability', 'Machine Learning', 'Deep Learning', 'Data Engineering'],
    duration: '8-12 months',
    level: 'beginner' as const,
  },
  {
    id: 'ai-engineer',
    title: 'AI Engineer',
    description: 'Build production AI systems with deep learning and NLP',
    courses: ['Python Advanced', 'Deep Learning', 'NLP', 'Computer Vision', 'MLOps'],
    duration: '10-14 months',
    level: 'intermediate' as const,
  },
  {
    id: 'fullstack-dev',
    title: 'Full-Stack Developer',
    description: 'Build complete web applications from frontend to backend',
    courses: ['Frontend Development', 'Backend Development', 'Database Design', 'DevOps Basics', 'Cloud Deployment'],
    duration: '8-10 months',
    level: 'beginner' as const,
  },
];
